### ISSUE TITLE
Update codebase to RC1

### ISSUE THREAD

**Issue by shrayasr** [dzimchuk/aspnet-middleware-sample#1]
This is a wonderful example on middlewares. But it is still in `beta5`. Would be nice to update it to `RC1` or at least have a branch for it. 

I could do this. Would you be open to taking PRs? 

Thanks again! :+1:

**Comment by dzimchuk** [comment]
Sure, a PR is going to be pretty much welcome ☺

**Comment by shrayasr** [comment]
Yay will get one your way in a couple of hours :+1:
